<!--Form-->
<div class="row">
    <div class="col s4">
    </div>
    <div class="col s4">
        <h5 class="center-align">Cadastro de Contatos</h5>
    </div>
    <div class="col s4">
    </div>
</div>

<div class="row">
    <div class="col s3">
    </div>

    <form class="col s6" id="form_create">

        <div class="row">
                <input id="form_id" type="text" name="id" style="display:none">
            <div class="input-field col s6">
                <input  id="form_nome" type="text" class="validate" name="nome">
                <label for="form_nome">Nome</label>
            </div>
            <div class="input-field col s6">
                <input  id="form_sobre_nome" type="text" class="validate" name="sobre_nome">
                <label for="form_sobre_nome">Sobrenome</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="form_endereco"   type="text" class="validate" name="endereco">
                <label for="form_endereco">Endereço</label>
            </div>
        </div>
            <div class="row">
                <div class="col s3">
                </div>
                <button class="btn waves-effect waves-light  blue darken-1" type="submit" id="submitButton">Submit
                    <i class="material-icons right">send</i>
                </button>
                <button class="btn waves-effect waves-light red" type="reset" name="action">Reset
                    <i class="material-icons right">clear_all</i>
                </button>
            </div>
    </form>
</div>
<!--Form-->

<div id="modal" class="modal bottom-sheet">
    <div class="modal-content">
        <p id="mensagem"></p>
    </div>
    <div class="modal-footer">
        <a href="#" class=" modal-action modal-close waves-effect waves-green btn-flat">Ok</a>
    </div>
</div>


<div class="row">
<table class="highlight striped bordered" id="contacts">
</table>
</div>


