<div class="container valign">
    <div class="row">
        <div class="col s12 m12">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <p class="flow-text">Desenvolvi esse "micro framework", utilizando a linguagem PHP com objetivo de implementar o teste solicitado. O código é bem desacoplado e limpo, sendo de fácil implementação e manutenção.</p>
                    <p class="flow-text">Atualmente trabalho com desenvolvedor full stack, utilizando php no backend com <a href="https://apigility.org" target="_blank">Apigility</a> e <a href="https://angularjs.org/" target="_blank">Angular Js</a> no front end.</p>
                    <p class="flow-text">Busco constantemente a melhoria do processo de desenvolvimento de software, estudando e aplicando boas praticas de desenvolvimento como "Código Limpo", Designer Patterns e PSR`s.</p>
                </div>
                <div class="card-action">
                    <a href="https://br.linkedin.com/in/tcristianoalves" target="_blank">Linkedin</a>
                    <a href="https://github.com/tiagoCristiano" target="_blank">GitHub</a>
                </div>
            </div>
        </div>
    </div>
</div>
