<html>
<header>
    <title>
        Teste - Tiago Cristiano Alves
    </title>
</header>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
<link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css">
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="assets/css/style.css" rel="stylesheet">
<body >
<header>
<nav class="blue darken-1">
    <div class="nav-wrapper">
        <a href="/" class="brand-logo center-align">Tiago Cristiano Alves</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/sobre">Sobre</a></li>
        </ul>
    </div>
</nav>
</header>
<main>
<div class="container">
<?= $this->content(); ?>
</div>
</main>
</body>
<footer class="page-footer" style="display: none">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Contato</h5>
                <p class="grey-text text-lighten-4">Email : tcristianoalves@outlook.com</p>
                <p class="grey-text text-lighten-4">Fone : (41) 9858-2967</p>
                <p class="grey-text text-lighten-4">Fone : (41) 3245-7516</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2016 Todos os direitos reservados
        </div>
    </div>
</footer>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="assets/js/index.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

</html>